import type { Metadata } from "next";
import { AuthProvider } from "@/providers/auth-provider";
import "./globals.css";
import { PatientProvider } from "@/providers/patient-provider";
import { TicketProvider } from "@/providers/ticket-provider";
import { ServiceTypeProvider } from "@/providers/serviceType-Provider";
import { VisitQueueProvider } from "@/providers/queue-provider";
import { StaffProvider } from "@/providers/staff-provider";
import { MedicalHistoryProvider } from "@/providers/medhistory-provider";

export const metadata: Metadata = {
  title: "CareLine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
    <html lang="en">
      <body>
        <AuthProvider>
          <StaffProvider>
          <PatientProvider>
            <TicketProvider>
              <MedicalHistoryProvider>
              <ServiceTypeProvider>
                <VisitQueueProvider>
                  {children}
                </VisitQueueProvider>
              </ServiceTypeProvider>
              </MedicalHistoryProvider>
            </TicketProvider>
          </PatientProvider>
          </StaffProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
